apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: prosody
        image: ghcr.io/two-first-names/prosody-docker  
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
        ports:
        - name: ftp
          containerPort: 5000
        - name: c2s
          containerPort: 5222
        - name: s2s
          containerPort: 5269
        - name: http
          containerPort: 5280
        - name: https
          containerPort: 5281
        - name: components
          containerPort: 5347
        - name: telnet
          containerPort: 5582
        volumeMounts:
        - name: prosody-config
          mountPath: /etc/prosody
        - name: prosody-data
          mountPath: /var/lib/prosody
        - name: prosody-tls
          mountPath: /certs
      volumes:
        - name: prosody-config
          configMap:
            name: prosody-config
        - name: prosody-tls
          secret:
            secretName: prosody-tls
        - name: prosody-data
          persistentVolumeClaim:
            claimName: prosody-data